name: Build mp3metadatafetcher

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ./multimedia/mp3metadatafetcher/Dockerfile --tag mp3metadatafetcher:$(date +%s)
