name: Build docker images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image for the mp3metadatafetcher
      run: docker build . --file ./multimedia/mp3metadatafetcher/Dockerfile --tag mp3metadatafetcher:$(date +%s)

    - name: Build the Docker image for the picturetool
      run: docker build . --file ./multimedia/picturetool/Dockerfile --tag picturetool:$(date +%s)
